package com.momentory.auth.kakao.infrastructure;

public enum KakaoApiErrorCode {
    INVALID_ACCESS_TOKEN,
    APP_ID_MISMATCH,
    USER_ID_MISMATCH,
    EMAIL_CONSENT_REQUIRED,
    EMAIL_UNAVAILABLE,
    KAKAO_API_SERVER_ERROR,
    KAKAO_API_NETWORK_ERROR,
    UNEXPECTED_KAKAO_RESPONSE
}
